package com.xworkz.runner;

import com.xworkz.external.*;

public class ExternalRunner {
    public static void main(String[] args) {
        Belt belt1 = new Belt();
        belt1.setBelt("Gucci","Leather","34","Buckle");
        System.out.println(belt1);
        Belt belt2 = new Belt();
        belt2.setBelt("Versace","Synthetic","34","Clip");
        System.out.println(belt2);
        Belt belt3 = new Belt();
        belt3.setBelt("Versace","Synthetic","34","Clip");
        System.out.println(belt3);
        boolean beltMatch = belt1.equals(belt2);
        boolean beltNotMatch = belt2.equals(belt3);
        System.out.println("Belt Match: "+ beltMatch);
        System.out.println("Belt Not Match:" + beltNotMatch);

        Chair chair1 = new Chair();
        chair1.setChair("Herman Miller","Mesh","Office",true);
        System.out.println(chair1);
        Chair chair2 = new Chair();
        chair2.setChair("Steelcase","Leather","Executive",false);
        System.out.println(chair2);
        Chair chair3 = new Chair();
        chair3.setChair("Steelcase","Leather","Executive",false);
        System.out.println(chair3);
        boolean chairMatch = chair1.equals(chair2);
        boolean chairNotMatch = chair2.equals(chair3);
        System.out.println("Chair Match: "+ chairMatch);
        System.out.println("Chair Not Match:" + chairNotMatch);

        Table table1 = new Table();
        table1.setTable("IKEA","Wood","Rectangle",4);
        System.out.println(table1);
        Table table2 = new Table();
        table2.setTable("Ashley Furniture","Glass","Round",1);
        System.out.println(table2);
        Table table3 = new Table();
        table3.setTable("Ashley Furniture","Glass","Round",1);
        System.out.println(table3);
        boolean tableMatch = table1.equals(table2);
        boolean tableNotMatch = table2.equals(table3);
        System.out.println("Table Match: "+ tableMatch);
        System.out.println("Table Not Match:" + tableNotMatch);

        Bed bed1 = new Bed();
        bed1.setBed("Sleep Number","Queen","Wood",true);
        System.out.println(bed1);
        Bed bed2 = new Bed();
        bed2.setBed("Tempur-Pedic","King","Metal",false);
        System.out.println(bed2);
        Bed bed3 = new Bed();
        bed3.setBed("Tempur-Pedic","King","Metal",false);
        System.out.println(bed3);
        boolean bedMatch = bed1.equals(bed2);
        boolean bedNotMatch = bed2.equals(bed3);
        System.out.println("Bed Match: "+ bedMatch);
        System.out.println("Bed Not Match:" + bedNotMatch);

        Sofa sofa1 = new Sofa();
        sofa1.setSofa("Joybird","Fabric",3,true);
        System.out.println(sofa1);
        Sofa sofa2 = new Sofa();
        sofa2.setSofa("West Elm","Leather",2,false);
        System.out.println(sofa2);
        Sofa sofa3 = new Sofa();
        sofa3.setSofa("West Elm","Leather",2,false);
        System.out.println(sofa3);
        boolean sofaMatch = sofa1.equals(sofa2);
        boolean sofaNotMatch = sofa2.equals(sofa3);
        System.out.println("Sofa Match: "+ sofaMatch);
        System.out.println("Sofa Not Match:" + sofaNotMatch);

        Bookshelf bookshelf1 = new Bookshelf();
        bookshelf1.setBookshelf("Sauder","Particleboard",5,72.0);
        System.out.println(bookshelf1);
        Bookshelf bookshelf2 = new Bookshelf();
        bookshelf2.setBookshelf("Bush Furniture","Wood",4,60.0);
        System.out.println(bookshelf2);
        Bookshelf bookshelf3 = new Bookshelf();
        bookshelf3.setBookshelf("Bush Furniture","Wood",4,60.0);
        System.out.println(bookshelf3);
        boolean bookshelfMatch = bookshelf1.equals(bookshelf2);
        boolean bookshelfNotMatch = bookshelf2.equals(bookshelf3);
        System.out.println("Bookshelf Match: "+ bookshelfMatch);
        System.out.println("Bookshelf Not Match:" + bookshelfNotMatch);

        Desk desk1 = new Desk();
        desk1.setDesk("Walker Edison","Wood",48.0,true);
        System.out.println(desk1);
        Desk desk2 = new Desk();
        desk2.setDesk("Zinus","Metal",55.0,false);
        System.out.println(desk2);
        Desk desk3 = new Desk();
        desk3.setDesk("Zinus","Metal",55.0,false);
        System.out.println(desk3);
        boolean deskMatch = desk1.equals(desk2);
        boolean deskNotMatch = desk2.equals(desk3);
        System.out.println("Desk Match: "+ deskMatch);
        System.out.println("Desk Not Match:" + deskNotMatch);

        Lamp lamp1 = new Lamp();
        lamp1.setLamp("TaoTronics","Floor",60,true);
        System.out.println(lamp1);
        Lamp lamp2 = new Lamp();
        lamp2.setLamp("Brightech","Table",40,false);
        System.out.println(lamp2);
        Lamp lamp3 = new Lamp();
        lamp3.setLamp("Brightech","Table",40,false);
        System.out.println(lamp3);
        boolean lampMatch = lamp1.equals(lamp2);
        boolean lampNotMatch = lamp2.equals(lamp3);
        System.out.println("Lamp Match: "+ lampMatch);
        System.out.println("Lamp Not Match:" + lampNotMatch);

        Mirror mirror1 = new Mirror();
        mirror1.setMirror("Umbra","Round",24.0,true);
        System.out.println(mirror1);
        Mirror mirror2 = new Mirror();
        mirror2.setMirror("Jonti-Craft","Square",36.0,false);
        System.out.println(mirror2);
        Mirror mirror3 = new Mirror();
        mirror3.setMirror("Jonti-Craft","Square",36.0,false);
        System.out.println(mirror3);
        boolean mirrorMatch = mirror1.equals(mirror2);
        boolean mirrorNotMatch = mirror2.equals(mirror3);
        System.out.println("Mirror Match: "+ mirrorMatch);
        System.out.println("Mirror Not Match:" + mirrorNotMatch);

        Clock clock1 = new Clock();
        clock1.setClock("Sharp","Alarm",true,true);
        System.out.println(clock1);
        Clock clock2 = new Clock();
        clock2.setClock("Sony","Wall",false,false);
        System.out.println(clock2);
        Clock clock3 = new Clock();
        clock3.setClock("Sony","Wall",false,false);
        System.out.println(clock3);
        boolean clockMatch = clock1.equals(clock2);
        boolean clockNotMatch = clock2.equals(clock3);
        System.out.println("Clock Match: "+ clockMatch);
        System.out.println("Clock Not Match:" + clockNotMatch);

        Painting painting1 = new Painting();
        painting1.setPainting("Van Gogh","Impressionism",1889,"Oil");
        System.out.println(painting1);
        Painting painting2 = new Painting();
        painting2.setPainting("Picasso","Cubism",1907,"Acrylic");
        System.out.println(painting2);
        Painting painting3 = new Painting();
        painting3.setPainting("Picasso","Cubism",1907,"Acrylic");
        System.out.println(painting3);
        boolean paintingMatch = painting1.equals(painting2);
        boolean paintingNotMatch = painting2.equals(painting3);
        System.out.println("Painting Match: "+ paintingMatch);
        System.out.println("Painting Not Match:" + paintingNotMatch);

        Plant plant1 = new Plant();
        plant1.setPlant("Snake Plant","Succulent","10in",false);
        System.out.println(plant1);
        Plant plant2 = new Plant();
        plant2.setPlant("Peace Lily","Flowering","12in",true);
        System.out.println(plant2);
        Plant plant3 = new Plant();
        plant3.setPlant("Peace Lily","Flowering","12in",true);
        System.out.println(plant3);
        boolean plantMatch = plant1.equals(plant2);
        boolean plantNotMatch = plant2.equals(plant3);
        System.out.println("Plant Match: "+ plantMatch);
        System.out.println("Plant Not Match:" + plantNotMatch);

        Guitar guitar1 = new Guitar();
        guitar1.setGuitar("Fender","Electric",6,"Sunburst");
        System.out.println(guitar1);
        Guitar guitar2 = new Guitar();
        guitar2.setGuitar("Gibson","Acoustic",6,"Natural");
        System.out.println(guitar2);
        Guitar guitar3 = new Guitar();
        guitar3.setGuitar("Gibson","Acoustic",6,"Natural");
        System.out.println(guitar3);
        boolean guitarMatch = guitar1.equals(guitar2);
        boolean guitarNotMatch = guitar2.equals(guitar3);
        System.out.println("Guitar Match: "+ guitarMatch);
        System.out.println("Guitar Not Match:" + guitarNotMatch);

        Piano piano1 = new Piano();
        piano1.setPiano("Yamaha","Grand",88,false);
        System.out.println(piano1);
        Piano piano2 = new Piano();
        piano2.setPiano("Casio","Digital",88,true);
        System.out.println(piano2);
        Piano piano3 = new Piano();
        piano3.setPiano("Casio","Digital",88,true);
        System.out.println(piano3);
        boolean pianoMatch = piano1.equals(piano2);
        boolean pianoNotMatch = piano2.equals(piano3);
        System.out.println("Piano Match: "+ pianoMatch);
        System.out.println("Piano Not Match:" + pianoNotMatch);

        Drum drum1 = new Drum();
        drum1.setDrum("Pearl","Acoustic","Maple",false);
        System.out.println(drum1);
        Drum drum2 = new Drum();
        drum2.setDrum("Roland","Electronic","Plastic",true);
        System.out.println(drum2);
        Drum drum3 = new Drum();
        drum3.setDrum("Roland","Electronic","Plastic",true);
        System.out.println(drum3);
        boolean drumMatch = drum1.equals(drum2);
        boolean drumNotMatch = drum2.equals(drum3);
        System.out.println("Drum Match: "+ drumMatch);
        System.out.println("Drum Not Match:" + drumNotMatch);

        Violin violin1 = new Violin();
        violin1.setViolin("Stradivarius","4/4","Spruce",1715);
        System.out.println(violin1);
        Violin violin2 = new Violin();
        violin2.setViolin("Yamaha","4/4","Maple",2020);
        System.out.println(violin2);
        Violin violin3 = new Violin();
        violin3.setViolin("Yamaha","4/4","Maple",2020);
        System.out.println(violin3);
        boolean violinMatch = violin1.equals(violin2);
        boolean violinNotMatch = violin2.equals(violin3);
        System.out.println("Violin Match: "+ violinMatch);
        System.out.println("Violin Not Match:" + violinNotMatch);

        Basketball basketball1 = new Basketball();
        basketball1.setBasketball("Spalding","7","Rubber",true);
        System.out.println(basketball1);
        Basketball basketball2 = new Basketball();
        basketball2.setBasketball("Wilson","7","Composite",false);
        System.out.println(basketball2);
        Basketball basketball3 = new Basketball();
        basketball3.setBasketball("Wilson","7","Composite",false);
        System.out.println(basketball3);
        boolean basketballMatch = basketball1.equals(basketball2);
        boolean basketballNotMatch = basketball2.equals(basketball3);
        System.out.println("Basketball Match: "+ basketballMatch);
        System.out.println("Basketball Not Match:" + basketballNotMatch);

        Football football1 = new Football();
        football1.setFootball("Nike","Official","Leather",true);
        System.out.println(football1);
        Football football2 = new Football();
        football2.setFootball("Adidas","Official","Composite",true);
        System.out.println(football2);
        Football football3 = new Football();
        football3.setFootball("Adidas","Official","Composite",true);
        System.out.println(football3);
        boolean footballMatch = football1.equals(football2);
        boolean footballNotMatch = football2.equals(football3);
        System.out.println("Football Match: "+ footballMatch);
        System.out.println("Football Not Match:" + footballNotMatch);

        TennisRacket tennisRacket1 = new TennisRacket();
        tennisRacket1.setTennisRacket("Wilson","4 3/8","100sq in","300g");
        System.out.println(tennisRacket1);
        TennisRacket tennisRacket2 = new TennisRacket();
        tennisRacket2.setTennisRacket("Babolat","4 1/4","98sq in","305g");
        System.out.println(tennisRacket2);
        TennisRacket tennisRacket3 = new TennisRacket();
        tennisRacket3.setTennisRacket("Babolat","4 1/4","98sq in","305g");
        System.out.println(tennisRacket3);
        boolean tennisRacketMatch = tennisRacket1.equals(tennisRacket2);
        boolean tennisRacketNotMatch = tennisRacket2.equals(tennisRacket3);
        System.out.println("TennisRacket Match: "+ tennisRacketMatch);
        System.out.println("TennisRacket Not Match:" + tennisRacketNotMatch);

        CricketBat cricketBat1 = new CricketBat();
        cricketBat1.setCricketBat("MRF","English Willow","1.2kg","Short");
        System.out.println(cricketBat1);
        CricketBat cricketBat2 = new CricketBat();
        cricketBat2.setCricketBat("SS","Kashmir Willow","1.1kg","Long");
        System.out.println(cricketBat2);
        CricketBat cricketBat3 = new CricketBat();
        cricketBat3.setCricketBat("SS","Kashmir Willow","1.1kg","Long");
        System.out.println(cricketBat3);
        boolean cricketBatMatch = cricketBat1.equals(cricketBat2);
        boolean cricketBatNotMatch = cricketBat2.equals(cricketBat3);
        System.out.println("CricketBat Match: "+ cricketBatMatch);
        System.out.println("CricketBat Not Match:" + cricketBatNotMatch);

        BadmintonRacket badmintonRacket1 = new BadmintonRacket();
        badmintonRacket1.setBadmintonRacket("Yonex","G5","85g","Head Heavy");
        System.out.println(badmintonRacket1);
        BadmintonRacket badmintonRacket2 = new BadmintonRacket();
        badmintonRacket2.setBadmintonRacket("Li-Ning","G4","83g","Even Balance");
        System.out.println(badmintonRacket2);
        BadmintonRacket badmintonRacket3 = new BadmintonRacket();
        badmintonRacket3.setBadmintonRacket("Li-Ning","G4","83g","Even Balance");
        System.out.println(badmintonRacket3);
        boolean badmintonRacketMatch = badmintonRacket1.equals(badmintonRacket2);
        boolean badmintonRacketNotMatch = badmintonRacket2.equals(badmintonRacket3);
        System.out.println("BadmintonRacket Match: "+ badmintonRacketMatch);
        System.out.println("BadmintonRacket Not Match:" + badmintonRacketNotMatch);

        Skateboard skateboard1 = new Skateboard();
        skateboard1.setSkateboard("Element","8.0","Independent","99A");
        System.out.println(skateboard1);
        Skateboard skateboard2 = new Skateboard();
        skateboard2.setSkateboard("Santa Cruz","8.25","Thunder","101A");
        System.out.println(skateboard2);
        Skateboard skateboard3 = new Skateboard();
        skateboard3.setSkateboard("Santa Cruz","8.25","Thunder","101A");
        System.out.println(skateboard3);
        boolean skateboardMatch = skateboard1.equals(skateboard2);
        boolean skateboardNotMatch = skateboard2.equals(skateboard3);
        System.out.println("Skateboard Match: "+ skateboardMatch);
        System.out.println("Skateboard Not Match:" + skateboardNotMatch);

        Surfboard surfboard1 = new Surfboard();
        surfboard1.setSurfboard("Channel Islands","6'0","Shortboard","Fiberglass");
        System.out.println(surfboard1);
        Surfboard surfboard2 = new Surfboard();
        surfboard2.setSurfboard("Firewire","7'2","Funboard","Epoxy");
        System.out.println(surfboard2);
        Surfboard surfboard3 = new Surfboard();
        surfboard3.setSurfboard("Firewire","7'2","Funboard","Epoxy");
        System.out.println(surfboard3);
        boolean surfboardMatch = surfboard1.equals(surfboard2);
        boolean surfboardNotMatch = surfboard2.equals(surfboard3);
        System.out.println("Surfboard Match: "+ surfboardMatch);
        System.out.println("Surfboard Not Match:" + surfboardNotMatch);

        YogaMat yogaMat1 = new YogaMat();
        yogaMat1.setYogaMat("Liforme","5mm","PVC",true);
        System.out.println(yogaMat1);
        YogaMat yogaMat2 = new YogaMat();
        yogaMat2.setYogaMat("Manduka","6mm","Rubber",false);
        System.out.println(yogaMat2);
        YogaMat yogaMat3 = new YogaMat();
        yogaMat3.setYogaMat("Manduka","6mm","Rubber",false);
        System.out.println(yogaMat3);
        boolean yogaMatMatch = yogaMat1.equals(yogaMat2);
        boolean yogaMatNotMatch = yogaMat2.equals(yogaMat3);
        System.out.println("YogaMat Match: "+ yogaMatMatch);
        System.out.println("YogaMat Not Match:" + yogaMatNotMatch);

        Dumbbell dumbbell1 = new Dumbbell();
        dumbbell1.setDumbbell("Bowflex","10kg","Neoprene",false);
        System.out.println(dumbbell1);
        Dumbbell dumbbell2 = new Dumbbell();
        dumbbell2.setDumbbell("CAP","10kg","Iron",false);
        System.out.println(dumbbell2);
        Dumbbell dumbbell3 = new Dumbbell();
        dumbbell3.setDumbbell("CAP","10kg","Iron",false);
        System.out.println(dumbbell3);
        boolean dumbbellMatch = dumbbell1.equals(dumbbell2);
        boolean dumbbellNotMatch = dumbbell2.equals(dumbbell3);
        System.out.println("Dumbbell Match: "+ dumbbellMatch);
        System.out.println("Dumbbell Not Match:" + dumbbellNotMatch);
    }
}
